
CREATE TABLE USUARIO
(
  CODIUSUARIO INT NOT NULL,
  NAMEUSUARIO VARCHAR(50),
  LASTUSUARIO VARCHAR(50),
  CARGOUSUARIO VARCHAR(50),
  PASSUSUARIO VARCHAR(50),
  DNIUSUARIO VARCHAR(50),
  FENAUSUARIO VARCHAR(30),
  DIRUSUARIO VARCHAR(50),
  TELUSUARIO INT,
  MAILUSUARIO VARCHAR(50)
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (CODIUSUARIO);

CREATE TABLE CINE(
  CODCINE INT NOT NULL,
  NOMCINE VARCHAR(50) NOT NULL,
  DIRCINE VARCHAR(50),
  MAILCINE VARCHAR(50)
);

ALTER TABLE CINE ADD CONSTRAINT PK_CINE PRIMARY KEY(CODCINE);

CREATE TABLE SALA
(
  CODCINE INT NOT NULL,
  CODSALA INT NOT NULL,
  NROSALA INT,
  CAPASALA INT,
  ATRISALA VARCHAR(40)

);
ALTER TABLE SALA ADD CONSTRAINT PK_SALA PRIMARY KEY (CODCINE, CODSALA);
CREATE INDEX IDX_SALA01 ON SALA(CODCINE);

ALTER TABLE SALA ADD CONSTRAINT FK_CINE_SALA FOREIGN KEY (CODCINE) REFERENCES CINE(CODCINE);

CREATE TABLE PELICULA
(
  CODPELICULA INT NOT NULL,
  NAMPELICULA VARCHAR(50),
  GENPELICULA VARCHAR(50),
  DURAPELICULA INT NOT NULL,
  CLASPELIULA INT,
  ESTADOPELICCULA INT
);


ALTER TABLE PELICULA ADD CONSTRAINT PK_PELICULA PRIMARY KEY (CODPELICULA);


CREATE TABLE CLIENTE
(
  CODICLIENTE INT NOT NULL,
  NAMECLIENTE VARCHAR(50),
  LASTCLIENTE VARCHAR(50),
  PASSCLIENTE VARCHAR(50),
  DNICLIENTE VARCHAR(20),
  FENACLIENTE VARCHAR(50),
  DIRCLIENTE VARCHAR(50),
  TLFCLIENTE INT,
  MAILCLIENTE VARCHAR(50)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODICLIENTE);

CREATE TABLE FUNCION
(
  CODFUNCION INT NOT NULL,
  CODPELICULA INT NOT NULL,
  HOINFUNCION VARCHAR(50),
  HOFIFUNCION VARCHAR(50)
);

ALTER TABLE FUNCION ADD CONSTRAINT PK_FUNCION PRIMARY KEY (CODFUNCION);

CREATE INDEX IDX_FUNCION01 ON FUNCION(CODPELICULA);

ALTER TABLE FUNCION ADD CONSTRAINT FK_PELICULA_FUNCION FOREIGN KEY (CODPELICULA) REFERENCES PELICULA(CODPELICULA);


CREATE TABLE BOLETO
(
  CODIBOLETO INT NOT NULL,
  FECHBOLETO VARCHAR(50),
  CODCINE INT NOT NULL,
  CODSALA INT NOT NULL,
  CODFUNCION INT NOT NULL
);

ALTER TABLE BOLETO ADD CONSTRAINT PK_BOLETO PRIMARY KEY (CODIBOLETO);

CREATE INDEX IDX_BOLETO01 ON BOLETO(CODCINE,CODSALA);
CREATE INDEX IDX_BOLETO02 ON BOLETO(CODFUNCION);

ALTER TABLE BOLETO ADD CONSTRAINT FK_SALA_BOLETO FOREIGN KEY (CODCINE, CODSALA) REFERENCES SALA(CODCINE, CODSALA);

ALTER TABLE BOLETO ADD CONSTRAINT FK_SALA_FUNCION FOREIGN KEY (CODFUNCION) REFERENCES FUNCION(CODFUNCION);
